### ISSUE TITLE
net.dreamlu.iot.mqtt.codec.MqttQoS.valueOf 重写无效？

### ISSUE THREAD

**Issue by manhere** [lets-mica/mica-mqtt#10]
### Other information（其他信息）
```
java.lang.IllegalArgumentException: No enum constant net.dreamlu.iot.mqtt.codec.MqttQoS.0
	at java.lang.Enum.valueOf(Enum.java:238)
	at net.dreamlu.iot.mqtt.codec.MqttQoS.valueOf(MqttQoS.java:23)
        ....
```

看来重写无效，直接使用了enum的valueOf
但是翻了翻，在 net.dreamlu.iot.mqtt.codec.MqttDecoder 中 MqttQoS.valueOf 却又能正确使用？

**Comment by ChunMengLu** [comment]
@manhere 确认下是不是类型不一致
